# Generated by Django 4.0.1 on 2022-01-24 11:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbalance',
            name='account_number',
            field=models.CharField(default=uuid.uuid4, max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='UserHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('amount', models.BigIntegerField()),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account_number', models.ForeignKey(db_column='account_number', on_delete=django.db.models.deletion.CASCADE, to='api.userbalance', to_field='account_number')),
                ('uid', models.ForeignKey(db_column='uid', on_delete=django.db.models.deletion.CASCADE, to='api.user', to_field='uid')),
            ],
        ),
    ]
