# Generated by Django 4.0.1 on 2022-01-24 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_userhistory_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserHistory',
            new_name='UserTransactionHistory',
        ),
    ]
