# Generated by Django 4.0.1 on 2022-02-04 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_userbalance_action_alter_userbalance_uid"),
    ]

    operations = [
        migrations.AddField(
            model_name="usertransactionhistory",
            name="trx_code",
            field=models.CharField(default="", max_length=255, unique=True),
        ),
    ]
